#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: ForgotMyCode

# Short bio or description (displayed in the header)
description: Nothing to see here

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars.githubusercontent.com/u/79061723?v=4

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

github:
  is_project_page: false
